//! End-to-end footage lifecycle on real files: import a clip generated by
//! FFmpeg, play it back through the lazy decode seam (never as embedded
//! samples), go offline and relink, generate a proxy, and undo the proxy
//! without losing the footage. Skips cleanly when FFmpeg/ffprobe are absent.

use bonaparte_model::Time;
use bonaparte_runtime::{EditorSession, RenderRequest};
use serde_json::json;

fn have_media_tools() -> bool {
    ["ffmpeg", "ffprobe"].iter().all(|tool| {
        std::process::Command::new(tool)
            .arg("-version")
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .status()
            .map(|s| s.success())
            .unwrap_or(false)
    })
}

/// The proxy dir rides the history-dir override; keep footage tests serial.
fn lock() -> std::sync::MutexGuard<'static, ()> {
    static SERIALIZED: std::sync::Mutex<()> = std::sync::Mutex::new(());
    SERIALIZED.lock().unwrap_or_else(|p| p.into_inner())
}

fn scratch() -> std::path::PathBuf {
    let dir = std::env::temp_dir().join(format!("bonaparte-footage-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    std::env::set_var("BONAPARTE_HISTORY_DIR", dir.join("hist"));
    std::fs::create_dir_all(dir.join("hist")).unwrap();
    dir
}

fn make_clip(path: &std::path::Path) {
    let status = std::process::Command::new("ffmpeg")
        .args([
            "-y",
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            "testsrc2=size=320x180:rate=24:duration=2",
            "-c:v",
            "libx264",
            "-pix_fmt",
            "yuv420p",
        ])
        .arg(path)
        .status()
        .unwrap();
    assert!(status.success(), "fixture clip must encode");
}

fn frame_sum(s: &EditorSession, secs: f64) -> u64 {
    let input = s
        .render_input(RenderRequest {
            comp_id: bonaparte_model::CompId(1),
            time: Time::from_secs_f64(secs),
            bypass_effects: false,
            layer_override: None,
            bit_depth: 8,
            output_space: Default::default(),
            source_quality: true,
            draft: false,
        })
        .unwrap();
    let frame = input.render().unwrap();
    frame.rgba.iter().map(|&b| b as u64).sum()
}

#[test]
fn footage_imports_plays_relinks_and_proxies() {
    if !have_media_tools() {
        eprintln!("skipping footage lifecycle: no FFmpeg");
        return;
    }
    let _serial = lock();
    let dir = scratch();
    let clip = dir.join("clip.mp4");
    make_clip(&clip);

    let mut session = EditorSession::default();
    let reply = session
        .command(
            "import_footage",
            json!({"path": clip.to_string_lossy(), "compId": 1}),
        )
        .expect("import succeeds");
    let _ = reply;

    // The asset exists with footage metadata, no embedded frame store.
    let state = session.command("state", json!({})).unwrap();
    let media = state["project"]["media"].as_object().unwrap();
    let (_, asset) = media
        .iter()
        .find(|(_, a)| a["footage"] != serde_json::Value::Null)
        .expect("footage asset");
    let footage = &asset["footage"];
    assert_eq!(footage["path"], json!(clip.to_string_lossy()));
    assert_eq!(footage["width"], json!(320));
    assert_eq!(footage["height"], json!(180));
    assert_eq!(footage["frame_rate"]["num"], json!(24));
    assert!(
        asset["video"].is_null(),
        "no baked frames — the file is the source"
    );
    assert!(
        !asset["embedded"].is_null(),
        "poster present for the library card"
    );
    assert!(footage["proxy_path"].is_null());

    // Full-framerate live playback: two moments show different pixels of the
    // moving test pattern; the same moment decodes identically (cache hit).
    let a = frame_sum(&session, 0.20);
    let b = frame_sum(&session, 1.40);
    assert_ne!(a, b, "footage moves through the live decode");
    assert_eq!(frame_sum(&session, 0.20), a, "cache serves repeats");

    // Media status sees the file.
    let status = session.command("media_status", json!({})).unwrap();
    assert_eq!(status[0]["online"], json!(true));
    assert_eq!(status[0]["proxy"], json!(false));
    let media_id = status[0]["media"].as_u64().unwrap();

    // Offline: rename the file away — status flips, frames become
    // unavailable, and nothing panics.
    let hidden = dir.join("gone.bin");
    std::fs::rename(&clip, &hidden).unwrap();
    let status = session.command("media_status", json!({})).unwrap();
    assert_eq!(status[0]["online"], json!(false), "offline detected");
    let media = session
        .project
        .media
        .get(&bonaparte_model::MediaId(media_id))
        .unwrap();
    let _ = media;

    // Relink to the moved file: same op surface an AI or the UI would use.
    session
        .command(
            "relink_media",
            json!({"media": media_id, "path": hidden.to_string_lossy()}),
        )
        .expect("relink works");
    let status = session.command("media_status", json!({})).unwrap();
    assert_eq!(status[0]["online"], json!(true), "back online after relink");
    assert_eq!(
        frame_sum(&session, 0.20),
        a,
        "pixels come back after relink"
    );

    // Proxy generation records itself through the same op (undoable).
    let before_effects = session.project.media.len();
    session
        .command("generate_proxy", json!({"media": media_id}))
        .expect("proxy generated");
    assert_eq!(session.project.media.len(), before_effects);
    let state = session.command("state", json!({})).unwrap();
    let media = state["project"]["media"].as_object().unwrap();
    let (_, asset) = media
        .iter()
        .find(|(_, a)| a["footage"] != serde_json::Value::Null)
        .unwrap();
    let proxy_path = asset["footage"]["proxy_path"].as_str().unwrap().to_string();
    assert!(
        std::path::Path::new(&proxy_path).is_file(),
        "proxy file on disk"
    );
    assert_eq!(asset["footage"]["proxy_size"], json!([160, 90]));
    let status = session.command("media_status", json!({})).unwrap();
    assert_eq!(status[0]["proxy"], json!(true));

    // Undo clears the proxy *reference*; redo restores it.
    session.command("undo", json!({})).unwrap();
    let state = session.command("state", json!({})).unwrap();
    let media = state["project"]["media"].as_object().unwrap();
    let (_, asset) = media
        .iter()
        .find(|(_, a)| a["footage"] != serde_json::Value::Null)
        .unwrap();
    assert!(
        asset["footage"]["proxy_path"].is_null(),
        "undo detaches the proxy"
    );
    session.command("redo", json!({})).unwrap();
    let state = session.command("state", json!({})).unwrap();
    let media = state["project"]["media"].as_object().unwrap();
    let (_, asset) = media
        .iter()
        .find(|(_, a)| a["footage"] != serde_json::Value::Null)
        .unwrap();
    assert!(
        !asset["footage"]["proxy_path"].is_null(),
        "redo reattaches the proxy"
    );

    // Walk all the way back: proxy, relink, then the import itself — the
    // footage asset disappears from the library entirely.
    session.command("undo", json!({})).unwrap();
    session.command("undo", json!({})).unwrap();
    session.command("undo", json!({})).unwrap();
    let state = session.command("state", json!({})).unwrap();
    let media = state["project"]["media"].as_object().unwrap();
    assert!(
        media
            .values()
            .all(|a| a["footage"] == serde_json::Value::Null),
        "undo of the import removes the footage binding entirely"
    );

    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn import_rejects_non_video_and_missing_files() {
    if !have_media_tools() {
        eprintln!("skipping: no FFmpeg");
        return;
    }
    let _serial = lock();
    let dir = scratch();
    let mut session = EditorSession::default();
    let err = session
        .command(
            "import_footage",
            json!({"path": dir.join("nope.mp4").to_string_lossy(), "compId": 1}),
        )
        .unwrap_err();
    assert!(err.contains("not found"), "friendly offline refusal: {err}");
    let png = dir.join("still.png");
    std::process::Command::new("ffmpeg")
        .args([
            "-y",
            "-v",
            "error",
            "-f",
            "lavfi",
            "-i",
            "color=c=red:size=64x64",
        ])
        .args(["-frames:v", "1"])
        .arg(&png)
        .status()
        .unwrap();
    let err = session
        .command(
            "import_footage",
            json!({"path": png.to_string_lossy(), "compId": 1}),
        )
        .unwrap_err();
    assert!(
        err.contains("still image"),
        "image misroute explained: {err}"
    );
    let _ = std::fs::remove_dir_all(&dir);
}
